### PR TITLE
Fixed a few things in Railcraft

### PR DESCRIPTION
**Pull request by CyanideCarrot**
Items
entity_bore renamed to bore
entity_cart_anchor_admin renamed to cart_worldspike_admin
entity_cart_anchor_personal renamed to cart_worldspike_personal
entity_cart_anchor_world renamed to cart_worldspike_standard
entity_cart_gift renamed to cart_gift
entity_cart_ic2_batbox renamed to cart_ic2_batbox
entity_cart_ic2_cesu renamed to cart_ic2_cesu
entity_cart_ic2_mfe renamed to cart_ic2_mfe
entity_cart_ic2_mfsu renamed to cart_ic2_mfsu
entity_cart_pumpkin renamed to cart_pumpkin
entity_cart_tank renamed to cart_tank
entity_cart_tnt_wood renamed to cart_tnt_wood
entity_cart_work renamed to cart_work
entity_mow_track_layer renamed to mow_track_layer
entity_mow_track_relayer renamed to mow_track_relayer
entity_mow_track_remover renamed to mow_track_remover
entity_mow_undercutter renamed to mow_undercutter

Blocks
anchor_admin renamed to worldspike_admin
anchor_personal renamed to worldspike_personal
anchor_world renamed to worldspike_standard
anchor_passive renamed to worldspike_passive
Created outfitted/unified folder
track.electric.junction renamed to junction_0 and moved to outfitted/unified/electric
track.junction renamed to junction_0 and moved to outfitted/unified/iron
track.reinforced.junction renamed to junction_0 and moved to outfitted/unified/reinforced
track.slow.junction renamed to junction_0 and moved to outfitted/unified/strap_iron

These changes are only the start of what needs to be done

### CODE REVIEW

**Comment by liach** [comment]
they are spikes not anchors

**Comment by CyanideCarrot** [comment]
I know
Thats one of the changes I made

**Comment by liach** [comment]
@bballboy2002 You need to change the pictures from anchors to screws, too.

**Comment by CyanideCarrot** [comment]
Well, if anyone else has the time to do that, go for it. But I don’t.

**Comment by StefanTT** [comment]
It would be good if you would combine the changes in one commit and not do a commit for every file.
I have the rights to merge the pull request but I have not yet verified if the changes are correct.

Quick update: I downloaded the current Railcraft and had a quick look. The change looks good, I will merge it.

**Comment by CyanideCarrot** [comment]
Github doesn’t let me delete one file at a time, and it doesn’t allow renaming files, so that’s the best I can do

**Comment by StefanTT** [comment]
You probably need to checkout the repository using a git client. The web interface is usually not meant for doing more than applying quick fixes.

It's ok as we can squash the commits when merging, but looking at the commits is not so easy if they are multiple commits, IMO.

**Pull request merged**
